twitter_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "127.0.0.1"
      port: 5432
      user: "postgres"
      pass: "example"
      dbname: "twitter"
      schema: "core"

